version: '3.8'
services:
  backlog-api:
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - GITHUB_TOKEN
      - TODOIST_TOKEN
    build:
      context: .
      dockerfile: Dockerfile
    image: dothem-backlog:latest
    ports:
      - "8080:8080"