name: Build and Push
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle clean build bootJar
      - name: Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: abialiauski/dothem-backlog
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}