name: Build PR
on:
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle clean build